[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":write"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

[keys.insert]
C-s = [":write", "normal_mode"]

[keys.normal.space]
"`" = "goto_last_accessed_file"
